development:
  adapter: postgresql
  encoding: unicode
  database: flipkart_development
  pool: 5
  host: localhost
  username: postgres
  password: "1234"

test:
  adapter: postgresql
  encoding: unicode
  database: flipkart_test
  pool: 5
  host: localhost
  username: postgres
  password: "1234"

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
